# master 配置
master:
  rpcPort: ":9099"

# chunk server 配置
chunk:
  port: "6789"

# client 配置
client:
  port: "6767"
  # PanicLevel Level = 0
  #	FatalLevel = 1
  #	ErrorLevel = 2
  #	WarnLevel = 3
  #	InfoLevel = 4
  #	DebugLevel = 5
  #	TraceLevel = 6
  logLevel: 4

# etcd config
etcd:
  endPoint: "172.18.0.20:2379"